/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gBabySol from "./GBaby.sol";
export type { gBabySol };
import type * as chocolateFactory from "./chocolate-factory";
export type { chocolateFactory };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Packets } from "./Packets";
export type { Randomizer } from "./Randomizer";
