/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gBabySol from "./GBaby.sol";
export type { gBabySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Cards } from "./Cards";
export type { Packets } from "./Packets";
export type { QuillAndInk } from "./QuillAndInk";
export type { Randomizer } from "./Randomizer";
