/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ABurnableUpgradeable } from "./ERC721ABurnableUpgradeable";
export type { ERC721AQueryableUpgradeable } from "./ERC721AQueryableUpgradeable";
export type { IERC721ABurnableUpgradeable } from "./IERC721ABurnableUpgradeable";
export type { IERC721AQueryableUpgradeable } from "./IERC721AQueryableUpgradeable";
