/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981Royalties__factory } from "./IERC2981Royalties__factory";
export { RoyaltiesUpgradable__factory } from "./RoyaltiesUpgradable__factory";
