/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICards,
  ICardsInterface,
} from "../../../../../contracts/src/contracts/interfaces/ICards";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICards__factory {
  static readonly abi = _abi;
  static createInterface(): ICardsInterface {
    return new utils.Interface(_abi) as ICardsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ICards {
    return new Contract(address, _abi, signerOrProvider) as ICards;
  }
}
