/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC2981Royalties } from "./IERC2981Royalties";
export type { RoyaltiesUpgradable } from "./RoyaltiesUpgradable";
