/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reservedSupplyUpgradeableSol from "./ReservedSupplyUpgradeable.sol";
export type { reservedSupplyUpgradeableSol };
export type { SupplyUpgradable } from "./SupplyUpgradable";
