/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminManager } from "./AdminManager";
export type { AdminManagerUpgradable } from "./AdminManagerUpgradable";
