/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as reservedSupplyUpgradeableSol from "./ReservedSupplyUpgradeable.sol";
export { SupplyUpgradable__factory } from "./SupplyUpgradable__factory";
