/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "IERC5267Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267Upgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "ERC1155Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Upgradeable__factory>;
    getContractFactory(
      name: "IERC1155MetadataURIUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURIUpgradeable__factory>;
    getContractFactory(
      name: "IERC1155ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "IERC1155Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Upgradeable__factory>;
    getContractFactory(
      name: "ERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Upgradeable__factory>;
    getContractFactory(
      name: "ERC721EnumerableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721EnumerableUpgradeable__factory>;
    getContractFactory(
      name: "IERC721EnumerableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721EnumerableUpgradeable__factory>;
    getContractFactory(
      name: "IERC721MetadataUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721MetadataUpgradeable__factory>;
    getContractFactory(
      name: "IERC721ReceiverUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ReceiverUpgradeable__factory>;
    getContractFactory(
      name: "IERC721Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Upgradeable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "EIP712Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712Upgradeable__factory>;
    getContractFactory(
      name: "ERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Upgradeable__factory>;
    getContractFactory(
      name: "IERC165Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165Upgradeable__factory>;
    getContractFactory(
      name: "AdminManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminManager__factory>;
    getContractFactory(
      name: "AdminManagerUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminManagerUpgradable__factory>;
    getContractFactory(
      name: "BalanceLimit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BalanceLimit__factory>;
    getContractFactory(
      name: "BalanceLimitUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BalanceLimitUpgradable__factory>;
    getContractFactory(
      name: "IERC2981Royalties",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2981Royalties__factory>;
    getContractFactory(
      name: "PriceUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PriceUpgradable__factory>;
    getContractFactory(
      name: "ReservedSupplyUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReservedSupplyUpgradable__factory>;
    getContractFactory(
      name: "RoyaltiesUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RoyaltiesUpgradable__factory>;
    getContractFactory(
      name: "SignerUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignerUpgradeable__factory>;
    getContractFactory(
      name: "UriManagerUpgradable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UriManagerUpgradable__factory>;
    getContractFactory(
      name: "Gbaby",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Gbaby__factory>;
    getContractFactory(
      name: "ICards",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICards__factory>;
    getContractFactory(
      name: "IRandomizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRandomizer__factory>;
    getContractFactory(
      name: "Packets",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Packets__factory>;
    getContractFactory(
      name: "Randomizer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Randomizer__factory>;
    getContractFactory(
      name: "IERC721ABurnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ABurnableUpgradeable__factory>;
    getContractFactory(
      name: "IERC721AUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721AUpgradeable__factory>;
    getContractFactory(
      name: "IOperatorFilterRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOperatorFilterRegistry__factory>;
    getContractFactory(
      name: "DefaultOperatorFiltererUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DefaultOperatorFiltererUpgradeable__factory>;
    getContractFactory(
      name: "OperatorFiltererUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OperatorFiltererUpgradeable__factory>;

    getContractAt(
      name: "OwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "IERC5267Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267Upgradeable>;
    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "ERC1155Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Upgradeable>;
    getContractAt(
      name: "IERC1155MetadataURIUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURIUpgradeable>;
    getContractAt(
      name: "IERC1155ReceiverUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155ReceiverUpgradeable>;
    getContractAt(
      name: "IERC1155Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Upgradeable>;
    getContractAt(
      name: "ERC721Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Upgradeable>;
    getContractAt(
      name: "ERC721EnumerableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721EnumerableUpgradeable>;
    getContractAt(
      name: "IERC721EnumerableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721EnumerableUpgradeable>;
    getContractAt(
      name: "IERC721MetadataUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721MetadataUpgradeable>;
    getContractAt(
      name: "IERC721ReceiverUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ReceiverUpgradeable>;
    getContractAt(
      name: "IERC721Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Upgradeable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "EIP712Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712Upgradeable>;
    getContractAt(
      name: "ERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165Upgradeable>;
    getContractAt(
      name: "IERC165Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165Upgradeable>;
    getContractAt(
      name: "AdminManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminManager>;
    getContractAt(
      name: "AdminManagerUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminManagerUpgradable>;
    getContractAt(
      name: "BalanceLimit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BalanceLimit>;
    getContractAt(
      name: "BalanceLimitUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BalanceLimitUpgradable>;
    getContractAt(
      name: "IERC2981Royalties",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2981Royalties>;
    getContractAt(
      name: "PriceUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PriceUpgradable>;
    getContractAt(
      name: "ReservedSupplyUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReservedSupplyUpgradable>;
    getContractAt(
      name: "RoyaltiesUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RoyaltiesUpgradable>;
    getContractAt(
      name: "SignerUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SignerUpgradeable>;
    getContractAt(
      name: "UriManagerUpgradable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UriManagerUpgradable>;
    getContractAt(
      name: "Gbaby",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Gbaby>;
    getContractAt(
      name: "ICards",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICards>;
    getContractAt(
      name: "IRandomizer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRandomizer>;
    getContractAt(
      name: "Packets",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Packets>;
    getContractAt(
      name: "Randomizer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Randomizer>;
    getContractAt(
      name: "IERC721ABurnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ABurnableUpgradeable>;
    getContractAt(
      name: "IERC721AUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721AUpgradeable>;
    getContractAt(
      name: "IOperatorFilterRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOperatorFilterRegistry>;
    getContractAt(
      name: "DefaultOperatorFiltererUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DefaultOperatorFiltererUpgradeable>;
    getContractAt(
      name: "OperatorFiltererUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OperatorFiltererUpgradeable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
